[ABOUT]
VERSION = 0.3
DESCRIPTION = iRacingBlackBoxMFDExtras, based on the original by Maxlmilian
AUTHOR = markhannon + Maxlmilian
URL = https://github.com/markhannon/iRacingBlackBoxMFDExtras
NAME = iRacingBlackBoxMFDExtras
; Original author: Maxlmilian
; Original URL: https://www.overtake.gg/members/maxlmilian.261948

[CORE]
LAZY = 0

[WINDOW_...]
PADDING = 0, 0
ID = main
FUNCTION_MAIN = windowMain
NAME = iRacingBlackBoxMFDExtras
ICON = icons/icon.png
FLAGS = NO_SCROLLBAR, NO_SCROLL_WITH_MOUSE, SETTINGS, NO_BACKGROUND, FADING, FIXED_SIZE
FUNCTION_SETTINGS = iRacingBlackBoxMFDExtras_Settings
SIZE=515.05197358131, 324.20398449898

[WINDOW_...]
PADDING = 0, 0
ID = lapTiming
FUNCTION_MAIN = windowLapTiming
NAME = Lap Timing
ICON = icons/icon.png
FLAGS = NO_SCROLLBAR, NO_SCROLL_WITH_MOUSE, NO_BACKGROUND, FADING, FIXED_SIZE
SIZE = 515.05197358131, 324.20398449898
DEFAULT_POSITION = 120, 120

[WINDOW_...]
PADDING = 0, 0
ID = standings
FUNCTION_MAIN = windowStandings
NAME = Standings
ICON = icons/icon.png
FLAGS = NO_SCROLLBAR, NO_SCROLL_WITH_MOUSE, NO_BACKGROUND, FADING, FIXED_SIZE
SIZE = 515.05197358131, 324.20398449898
DEFAULT_POSITION = 160, 160

[WINDOW_...]
PADDING = 0, 0
ID = relative
FUNCTION_MAIN = windowRelative
NAME = Relative
ICON = icons/icon.png
FLAGS = NO_SCROLLBAR, NO_SCROLL_WITH_MOUSE, NO_BACKGROUND, FADING, FIXED_SIZE
SIZE = 515.05197358131, 324.20398449898
DEFAULT_POSITION = 200, 200

