[ABOUT]
VERSION = 0.3
DESCRIPTION = iRacingBlackBoxMFDExtras, based on the original by Maxlmilian
AUTHOR = markhannon + Maxlmilian
URL = https://github.com/markhannon/iRacingBlackBoxMFDExtras
NAME = iRacingBlackBoxMFDExtras
; Original author: Maxlmilian
; Original URL: https://www.overtake.gg/members/maxlmilian.261948

[WINDOW_...]
PADDING = 0, 0
ID = main
FUNCTION_MAIN = windowMain
NAME = iRacingBlackBoxMFDExtras
ICON = icons/icon.png
FLAGS = NO_SCROLLBAR, NO_SCROLL_WITH_MOUSE, SETTINGS, NO_BACKGROUND, FADING, FIXED_SIZE
FUNCTION_SETTINGS = iRacingBlackBoxMFDExtras_Settings
SIZE=515.05197358131, 324.20398449898

